**שימו לב**: על מנת להריץ את התאים ב-Live Code, יש לייבא תחילה את ספריית `numpy` ע"י הרצת השורת הבאה:

In [4]:
import numpy as np
import utils.load_auxilary_files # This will load the files used for this notebook

# אתחול מערכים ב-`numpy`

In [1]:
%%html
<iframe width="560" height="315" src="https://www.youtube.com/embed/Dbg-j-F2mtM" title="numpy 2" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>

```{admonition}  טקסט המופיע למטה בסגול מציין קטעים המופיעים בסרטון    
:class: custom-text
ניתן להיעזר בו כדי לחזור על התכנים או לעיין בהם שוב.
```

<span class=custom-text-content> 

האובייקט המרכזי בספריית `numpy` הוא **מערך רב־ממדי (ndarray), או `np.array`**.  
המערך הוא מבנה נתונים הומוגני, **כלומר כל האיברים שבו הם מאותו טיפוס**. למשל, כולם מספרים שלמים או כולם שברים עשרוניים.  
ניתן לחשוב על מערך גם כוקטור חד מימדי או כמטריצה של איברים (בדרך כלל מספרים).  
ניתן לייצג במערכי `numpy` גם מבנים רב מימדיים כמו מטריצה תלת מימדית, אך לא נעסוק בכך במסגרת נושא זה.

בחלק זה נכיר דרכים שונות ליצור מערכים חדשים, ונלמד מעט פעולות אריתמתיות שניתן לבצע על מערכים כאלו.

</span>

## יצירת מערך חדש

<span class=custom-text-content> 

באופן אינטואיטיבי, ניתן ליצור מערך על ידי המרה מרשימה (וקטור חד מימדי) או מרשימה מקוננת (מטריצה):

</span>

In [5]:
a = np.array([0, 1])
print('a is:' , a)
b = np.array([[1, 2 , 3], [4, 5, 6]])
print('b is: \n' , b)
c = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])
print('c is: \n' , c)

a is: [0 1]
b is: 
 [[1 2 3]
 [4 5 6]]
c is: 
 [[0.1 0.2 0.3]
 [0.4 0.5 0.6]]


```{admonition} **שימו לב**
:class: error

כדי ליצור ndarray שמייצג מטריצה, צריך לוודא שכל הרשימות המקוננות בעלות אורך זהה. אחרת, לא נקבל מטריצה.

```



 

## פעולות אריתמטיות פשוטות

<span class=custom-text-content> 

בהנתן 2 מטריצות בעלות אותם מימדים, ניתן להפעיל עליהן פעולות אריתמטיות.
לדוגמא, חיבור שתי מטריצות cell by cell מתבצע על-ידי פעולת החיבור.

</span>

In [6]:
b = np.array([[1, 2 , 3], [4, 5, 6]])
c = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])
print(b+c)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]


<span class=custom-text-content> 

**שימו לב!**
פעולת חיבור בין שתי מטריצות מוגדרת אך אם המימדים זהים.   
אם ננסה לבצע חיבור על שתי מטריצות בעלות מימדים שונים, הפעולה תכשל:

</span>

In [7]:
a = np.array([0, 1])
b = np.array([[1, 2 , 3], [4, 5, 6]])
print(a+b)

ValueError: operands could not be broadcast together with shapes (2,) (2,3) 

<span class=custom-text-content> 

יוצא דופן לכך הוא מקרה בו מחברים **וקטור** (חד מימדי) עם מטריצה שאורך שורותיה (כלומר, מס' העמודות) זהה לאורך הוקטור:
לפעולה כזו קוראים גם **broadcasting**.

</span>

In [8]:
b = np.array([[1, 2 , 3], [4, 5, 6]])
d = np.array([10,10,10])
print(b+d)

[[11 12 13]
 [14 15 16]]


## דרכים נוספות ליצירת מערכים

<span class=custom-text-content> 

מעבר להמרה מרשימות, קיימות פונקציות שמסייעות לנו לאתחל מערך חדש בצורה פשוטה.   
שתי פונקציות נפוצות המשמשות לצורך זה הן `zeros` ו-`ones`, המקבלות כארגומנט ראשון את **מימדי הוקטור או המטריצה** שרוצים לאתחל.

</span>

In [9]:
print(np.zeros(7))

[0. 0. 0. 0. 0. 0. 0.]


אם נרצה ליצור מטריצה, נעביר tuple של מימדי המטריצה (מספר השורות ומספר העמודות). שימו לב לסוגריים הנוספים עבור ה-tuple.

</span>

In [10]:
print(np.ones((2,5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


```{admonition} **שימו לב!**
:class: error
הנקודות שמופיעות אחרי האפסים רומזות לנו שהערכים במטריצה הם מטיפוס `float`.   
```

<span class=custom-text-content> 

אם נרצה לשנות את איתחול המטריצה כך שתכיל ערכים מטיפוס אחר, נגדיר לפונקציה את הפרמטר `dtype`. לדוגמא, באתחול המטריצה להלן:

</span>

In [11]:
print(np.ones((2,3), dtype=int))

[[1 1 1]
 [1 1 1]]


```{admonition} **עצרו וחישבו:**  מה אם נרצה לאתחל את המטריצה במספר קבוע, שאינו 0 או 1? הרי לא הגיוני לממש twos, threes וכן הלאה.
:class: dropdown, caution

הדרך הכי אינטואיטיבית (למי שנושם אלגברה ליניארית), הוא להשתמש בכפל מטריצה במספר (סקלאר): 
``` python
3.17*np.ones((3,2))
```

### מערכים לא אחידים

<span class=custom-text-content> 

נניח שנרצה לייצר מערך שמייצג **סדרה של מספרים**.  
היינו יכולים ליצור **רשימה** המכילה סדרה זו ולהעביר אותה ל`np.array`.   

</span>

```{admonition} **עצרו וחישבו:**  כיצד הייתם יוצרים סדרה של מספרים?
:class: dropdown, note

באמצעות `range` כמובן!  
נזכיר כי הקלט ל`range` הוא אינדקס ההתחלה (כולל), אינדקס הסיום (לא כולל) והקפיצה של כל צעד בסדרה.  

```

<span class=custom-text-content> 

מסתבר ש-`numpy` מימשו עבורנו כבר פונקציה דומה בשם `arange` המבצעת פעולה דומה וחוסכת לנו את פעולת ההמרה:  

</span>

In [12]:
print(np.arange(1, 10, 1))

[1 2 3 4 5 6 7 8 9]


<span class=custom-text-content> 

לעומת `range` שראינו, באמצעות `arange` ניתן ליצור **סדרות עם מספרים שבריים (`float`)**: 

</span>

In [13]:
print(np.arange(1.5, 2.5, 0.1))

[1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4]


### מערכים עם מספרים אקראיים

<span class=custom-text-content> 

כעת נראה איתחול של וקטורים ומטריצות עם **ערכים אקראיים**.

באמצעות `np.random.random`, אשר מקבלת `tuple` המייצג את מימדי המטריצה, ניתן לאתחל ערכים אקראיים שבריים בין 0 ל-1.

</span>

In [14]:
rand_arr=np.random.random((2,5))
print(rand_arr)

[[0.55613899 0.38608262 0.79545814 0.60262787 0.25401993]
 [0.40173374 0.83686213 0.16065438 0.08035446 0.93287565]]


```{admonition} **נסו בעצמכם**
:class: caution
הריצו את התא למעלה בשנית. האם קיבלתם את אותם מספרים?

```

#### ואיך נוכל ליצור מערכים אקראיים בטווח מספרים אחר?

<span class=custom-text-content> 

באמצעות כפל בסקלאר ניתן "למתוח" או "לכווץ" את הטווח.

</span>

In [15]:
print(rand_arr*2)

[[1.11227799 0.77216523 1.59091628 1.20525574 0.50803985]
 [0.80346748 1.67372426 0.32130875 0.16070892 1.86575131]]


In [16]:
print(rand_arr*0.5) 

[[0.2780695  0.19304131 0.39772907 0.30131393 0.12700996]
 [0.20086687 0.41843106 0.08032719 0.04017723 0.46643783]]


<span class=custom-text-content> 

ובאמצעות הוספת סקלאר ניתן "להזיז" את טווח הערכים. 

</span>

In [17]:
print(-4+rand_arr) 

[[-3.44386101 -3.61391738 -3.20454186 -3.39737213 -3.74598007]
 [-3.59826626 -3.16313787 -3.83934562 -3.91964554 -3.06712435]]


<span class=custom-text-content> 

למעשה, ע"י הוספת והכפלה ניתן להגיע לכל טווח שנרצה. לדוגמא:

</span>

In [18]:
print(3+rand_arr*0.2)

[[3.1112278  3.07721652 3.15909163 3.12052557 3.05080399]
 [3.08034675 3.16737243 3.03213088 3.01607089 3.18657513]]


**נסו בעצמכם!** צרו מערך בעל 3 שורות ו2 עמודות המכיל ערכים אקראיים בטווח 10-12:

In [19]:
# Write your code here

```{admonition} **לחצו כאן כדי לצפות בפתרון**
:class: dropdown, tip

``` python
rand_arr=np.random.random((3,2))
print(rand_arr*2 + 10)

```

<span class=custom-text-content> 

ואם נרצה **ערכים רנדומליים שלמים?** לצורך כך, נוכל להשתמש `np.random.randint`. 
כאן, הערכים הראשונים שנעביר מייצגים את **טווח המספרים השלמים** מהם נרצה להגריל את המספר האקראי שלנו: המספר הראשון הוא תחילת הטווח (כולל), והשני סוף הטווח (לא כולל).   
הפרמטר השלישי הוא טאפל המייצג את **מימדי הוקטור/מטריצה**.

</span>

In [20]:
print(np.random.randint(0,7,(5,2)))

[[4 5]
 [2 6]
 [0 5]
 [6 0]
 [3 5]]
