**שימו לב**: על מנת להריץ את התאים ב-Live Code, יש לייבא תחילה את ספרית `numpy` ע"י הרצת השורת הבאה

In [1]:
import numpy as np
import utils.load_auxilary_files # This will load the files used for this notebook

['dog_noised.png', 'sunday.txt', 'orders_3_2024.csv', 'dialation_2.png', 'woman_noised.png', 'erosion_2.png', 'infile1.txt', 'notebook_resources.zip', 'countries-of-the-world.csv', 'ex1.csv', 'StudentsGrades.csv', 'out.txt', 'dog.png', 'foods.txt', 'dialation.png', '__MACOSX', 'evil_morty_segmentation.png', 'products2.csv', 'orders_2_2024.csv', 'evil_morty_1.png', 'monday.txt', 'ship.png', 'koala.png', 'baby.png', 'erosion.png', 'evil_morty_change_noised.png', 'orders_4_2024.csv', 'ex2.csv', 'evil_morty_change.png', 'evil_morty_change_3.png', 'infile2.txt', 'witcher_1.csv', 'witcher_2.csv']


# שאלות ממבחני עבר

[Exam 2023-2024 semester A Moed A](https://courses.cs.tau.ac.il/pyProg/2425a/exams/exam2324a_moedA.pdf)

3.A

In [2]:
def get_nth_mask(im, n, idx):
    size = (im.max() - im.min()) / n
    mask_high = im >= (im.min() + size * idx)
    mask_low = im <= (im.min() + size * (idx + 1))
    return mask_high * mask_low

In [3]:
im = np.array([[3,5,9],[8,1,2],[7,6,4]])
print(get_nth_mask(im, 3, 0))

[[ True False False]
 [False  True  True]
 [False False False]]


3.B

In [4]:
def get_n_valued_image(im, n):
    out = np.zeros(im.shape)
    for i in range(n):
        mask = get_nth_mask(im, n, i)
        out[mask] = im[mask].mean()
    return out

In [5]:
im = np.array([[3,5,9],[8,1,2],[7,6,4]])
print(get_n_valued_image(im, 3))

[[2. 5. 8.]
 [8. 2. 2.]
 [8. 5. 5.]]


3.C

In [6]:
def compute_entropy(im):
    image_pixels = im.flatten()
    bin_prob = np.bincount(image_pixels) / (image_pixels.shape[0])
    bin_prob = bin_prob[bin_prob != 0]
    return (-bin_prob * np.log2(bin_prob)).sum()

In [7]:
im = np.array([[1,4],[4,8]])
compute_entropy(im)

np.float64(1.5)

what is entropy https://en.wikipedia.org/wiki/Entropy_(information_theory):
- you are **not required** to understand the math behind such formulas
- you are **required** to be able to implement a given formula such as entropy

3.D

In [8]:
im = np.arange(6).reshape((2, 3))
print((im[:, ::2] ** 2).sum())

38
