In [5]:
import urllib.request
import zipfile
import os
import ssl 

try:
    os.mkdir("files")
except:
    pass

ssl._create_default_https_context = ssl._create_unverified_context

with urllib.request.urlopen('https://courses.cs.tau.ac.il/pyProg/2425a/resources/notebook_resources.zip') as f:
    content = f.read()

with open('files/notebook_resources.zip', 'wb') as f:
    f.write(content)

with zipfile.ZipFile('files/notebook_resources.zip', 'r') as zip_ref:
    zip_ref.extractall('files')

print(os.listdir('files'))

import numpy as np

['baby.png', 'countries-of-the-world.csv', 'dialation.png', 'dialation_2.png', 'dog.png', 'dog_noised.png', 'erosion.png', 'erosion_2.png', 'evil_morty_1.png', 'evil_morty_change.png', 'evil_morty_change_3.png', 'evil_morty_change_noised.png', 'evil_morty_segmentation.png', 'ex1.csv', 'ex2.csv', 'koala.png', 'notebook_resources.zip', 'orders_2_2024.csv', 'orders_3_2024.csv', 'orders_4_2024.csv', 'products2.csv', 'ship.png', 'StudentsGrades.csv', 'witcher_1.csv', 'witcher_2.csv', 'woman_noised.png', '__MACOSX']


# יצירת מערך חדש

## ייצוג מערכים בNumpy באמצעות ndarray/`np.array`

האובייקט המרכזי בספריית Numpy הוא **מערך רב־ממדי (ndarray), או `np.array`**. זהו מבנה נתונים הומוגני, **כלומר כל האיברים שבו הם מאותו טיפוס**. למשל, כולם מספרים שלמים או כולם שברים עשרוניים). ניתן לחשוב עליו גם כוקטור חד מימדי או מטריצה של איברים (בדרך כלל מספרים). ניתן לייצג במערכי Numpy גם מבנים רב מימדיים כמו מטריצה תלת מימדית, אך לא נעסוק בכך במסגרת נושא זה.

באופן אינטואיטיבי, ניתן ליצור מערך מרשימה (וקטור חד מימדי) או מרשימה מקוננת (מטריצה):

In [5]:
a = np.array([0, 1])
print('a is' , a)
b = np.array([[1, 2 , 3], [4, 5, 6]])
print('b is \n' , b)
c = np.array([[0.1, 0.2, 0.3], [0.4, 0.5, 0.6]])
print('c is \n' , c)


a is [0 1]
b is 
 [[1 2 3]
 [4 5 6]]
c is 
 [[0.1 0.2 0.3]
 [0.4 0.5 0.6]]


```{admonition} **שימו לב**
:class: warning

אם יוצרים מטריצה, אורכי הרשימות המקוננות צריכים להיות זהים (אחרת זו אינה מטריצה)

```



 

בהנתן 2 מטריצות בעלות אותה הצורה ניתן להפעיל עליהן פעולות אריתמטיות  

In [121]:
print(b+c)

[[1.1 2.2 3.3]
 [4.4 5.5 6.6]]


אך אם המימדים אינם זהים, הפעולה תכשל

In [122]:
print(a+b)

ValueError: operands could not be broadcast together with shapes (2,) (2,3) 

יוצא דופן לכך הוא מקרה בו מחברים וקטור חד מימדי עם מטריצה שאורך שורותיה (כלומר, מס' העמודות) זהה לאורך הוקטור:

In [6]:
print(b+np.array([10,10,10]))

[[11 12 13]
 [14 15 16]]


בנוסף, קיימות פונקציות שמסייעות לנו לאתחל מערך חדש בצורה פשוטה.   
שתי פונקציות נפוצות המשמשות לצורך זה הן `zeros` ו-`ones`, המקבלות כארגומנט ראשון את מימדי הוקטור או המטריצה שרוצים לאתחל.

In [8]:
print(np.zeros(7))

[0. 0. 0. 0. 0. 0. 0.]


שימו לב בהדפסה לעיל לנקודות שבאות לאחר האפסים. נקודות אלו באות לרמוז לנו שהערכים במטריצה הם מטיפוס `float`.   
אם נרצה לשנות את איתחול המטריצה, כך שיהיה עם טיפוס אחר, נוכל לעשות זאת באמצעות הפרמטר `dtype`. לדוגמא, באתחול המטריצה להלן:

In [9]:
print(np.ones((2,3), dtype=int))

[[1 1 1]
 [1 1 1]]


ומה אם נרצה לאתחל את המטריצה במספר שאינו 0 או 1? ישנן מספר דרכים לעשות זאת בNumpy. אך הדרך הכי אינטואיטיבית למי שלמד אלגברה ליניארית ומבצע אנליזות נומריות באמצעות הספריה הוא כפל מטריצה במספר (סקלאר): 

In [12]:
print(3.17*np.ones((3,2)))

[[3.17 3.17]
 [3.17 3.17]
 [3.17 3.17]]


ומה אם נרצה לאתחל מערך בצורה לא אחידה? לדוגמא, בסדרה של מספרים?

נוכל ליצור רשימה המכילה סדרה זו ולהעביר אותה ל`np.array`. 

כיצד הייתם יוצרים סדרה ארוכה כזו? לדוגמא, של כל המספרים מ0 עד 1000? באמצעות `range` כמובן!

נזכיר כי הקלט ל`range` הוא אינדקס ההתחלה (כולל), אינדקס הסיום (לא כולל) והקפיצה של כל צעד בסדרה

מסתבר ש`numpy` מימשו עבורנו כבר פונקציה דומה בשם `arange` המבצעת פעולה דומה וחוסכת לנו את פעולת ההמרה:

In [15]:
print(np.arange(1, 10, 1))

[1 2 3 4 5 6 7 8 9]


כשדרוג נוסף לפונקצית `range` שראינו, ניתן באמצעות `arange` ליצור סדרות עם מספרים שבריים (`float`): 

In [16]:
print(np.arange(1.5, 2.5, 0.1))

[1.5 1.6 1.7 1.8 1.9 2.  2.1 2.2 2.3 2.4]


לבסוף, נראה איתחול של וקטורים ומטריצות ב**ערכים אקראיים**.

באמצעות `np.random.random`, בהנתן מימדי המטריצה, ניתן לאתחל ערכים אקראיים שבריים בין 0 ל-1

In [19]:
rand_arr=np.random.random((2,5))
print(rand_arr)

[[0.60736756 0.68662925 0.26965962 0.95609409 0.66257245]
 [0.51312364 0.62507254 0.20818247 0.52921081 0.00230717]]


באמצעות כפל בסקלאר ניתן "למתוח" או "לכווץ" את הטווח

In [20]:
print(rand_arr*2) # ranging between 0 to 2

[[1.21473511 1.37325849 0.53931923 1.91218818 1.32514489]
 [1.02624728 1.25014508 0.41636494 1.05842162 0.00461433]]
[[0.30368378 0.34331462 0.13482981 0.47804704 0.33128622]
 [0.25656182 0.31253627 0.10409123 0.2646054  0.00115358]]


In [ ]:
print(rand_arr*0.5) # ranging between 0 to 0.5

ובאמצעות הוספת סקלאר ניתן "להזיז" את טווח הערכים 

In [ ]:
print(4+rand_arr) # ranging between 4 to 5

In [21]:
print(-4+rand_arr) # ranging between -4 to -3

[[-3.39263244 -3.31337075 -3.73034038 -3.04390591 -3.33742755]
 [-3.48687636 -3.37492746 -3.79181753 -3.47078919 -3.99769283]]


למעשה, ע"י הוספת והכפלה ניתן להגיע לכל טווח שנרצה. לדוגמא:

In [ ]:
print(3+rand_arr*0.2) # ranging between 3 to 3.2 

ואם נרצה ערכים רנדומליים שלמים? לצורך כך, נוכל להשתמש `np.random.randint`. 
כאן, הערכים הראשונים שנעביר מייצגים את טווח המספרים השלמים מהם נרצה להגריל את המספר האקראי שלנו: המספר הראשון הוא תחילת הטווח (כולל), והשני סוף הטווח (לא כולל).   
הפרמטר השלישי הוא מימדי הוקטור/מטריצה

In [22]:
print(np.random.randint(0,7,(5,2)))

[[6 2]
 [2 1]
 [6 1]
 [0 6]
 [1 2]]
